In [5]:
import numpy as np

In [3]:

arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


In [5]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.full((3, 4), 8)

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

In [8]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [6]:
np.arange(1, 100, 9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [9]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [15]:
print("Shape:", arr.shape)   # (2, 3) → 2 rows, 3 columns
print("Size:", arr.size)     # 6 → total elements
print("Dimensions:", arr.ndim) # 2 → 2D arrayf
print("Data type:", arr.dtype) # int64 (or int32 on Windows)

Shape: (2, 4)
Size: 8
Dimensions: 2
Data type: int64


In [16]:
flattend = arr.flatten()

In [17]:
print(flattend)

[1 2 3 4 5 6 7 8]


In [18]:
reshape = arr.reshape(4, 2)

In [19]:
print(reshape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [20]:
arr_float = arr.astype(np.float32)

In [21]:
print(arr_float)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]
