In [4]:
import numpy as np

In [5]:
arr = np.array([1 , 2, 3, 4])

In [6]:
print(arr[0])
print(arr[-1])

1
4


In [17]:
arr = np.array([1, 2, 3, 4, 5, 66, 89])

idx = arr%2 == 0
x = arr[idx]
print(x)

[ 2  4 66]


In [13]:
mask = arr>2
print(arr[mask])

[ 3  4  5 66 89]


In [18]:
# Simulating a dataset (5 samples, 3 features)
data = np.array([[10, 20, 30],
                 [15, 25, 35],
                 [20, 30, 40],
                 [25, 35, 45],
                 [30, 40, 50]])

# Calculating mean and standard deviation for each feature (column)
mean = data.mean(axis=0)
std = data.std(axis=0)

# Normalizing the data using broadcasting
normalized_data = (data - mean) / std

print(normalized_data)

[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]
